server:
  port: 8090

spring:
  config:
    import: optional:file:./etc/secrets/config.properties,optional:file:/etc/secrets/config.properties
  application:
    name: sso-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sso_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
  cache:
    type: redis
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:localhost:9092}
    properties:
      security:
        protocol: SSL
      ssl:
        truststore:
          type: PEM
          location: ${KAFKA_TRUSTSTORE_PATH:${user.dir}/src/main/resources/ca.pem}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH:${user.dir}/src/main/resources/ca.pem}
          password: changeit

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  jwt:
    issuer: ordernest-sso
    access-token-minutes: 15
    refresh-token-days: 7
    key-id: sso-key-1
    private-key-base64: ${JWT_PRIVATE_KEY_BASE64:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSSe+1Gb6JHVvZrgSUlNnsWkh8jsAOtMtVhopkxbRTnrjcuHCCduCdJ5I1vdRaeie8XaakA63aUig0tD1TbK//l8mH0IzGZQjhXj4e3gurFq9A0q5iSU65BwVw3K+vktgKvypXfrTQfv8bFQgLeb5RbcXcldesn8BeZRkG1/y7PFcMhzJD1XtwULHVvl39cw2ZEVc8CYkyzurvPZEcLy9GG1zPdV1H48vu9ybEz2atbzqpCYialVk6OelIGHbT/5XIKuisdMiXrO4PYBjsoxpwcpi+cZDFCm71FPrT2P29wo6sX7R15+V1+/jMVitYDjo+5aDNqHkb8+EiR8eYMYLPAgMBAAECggEAJwNVh90vVqPOOwvISMJ2zZ0QTp9zLSdIg+TyfvCY3FyZgkVrhiDE2hMR0ouVvnVkMtOTC2GtWtAcKm7346bJ3hrMZjiALXxoEduYncRnGMYcHGQZux1LkBMn5MDkjSeqkg/WLKZSqE2vSVh1Bh//eX7qktpvyVRX7YtHAdiHSDr6vbeWe4deFvjPq+g+4iabil/JOvlpKbpIU5alc0sRjAdSdSyLn3KwmKmVp94xSIrL4oiEBJ9+uKP5Eyg2yGoI8m+wQhg5NJ4c8OjVYNVBOdux5vwdCqakqAgxMfQmECLo7KJEUkyWkcNTFpKFPwCdaaMT/qVaLf+kGdrivS5URQKBgQDXexP3rELhGvKOoVkpwZdIMH28Hg6q9M6o/ELy1Z4nrUPwXM1367rvggIoq9Si9SZGt+3VP97i4w98Jv2NP7Mz9D9mG65nEavVjzpznUvUvugBkt/W1UBvDG4fsdGP5F9wkkc2tHeMKDvDQjEUgmjQgR7wjZcogbQYyUN7UnzycwKBgQD51OzZpr8BfzeSZIoz1gEGOjd0nLVZ9bWCqkPr1XfMYI2YAC2yFzUquPvOyZgQoTI8YBpaG9zUAylr79yEOizgO8WjWmPAfxS3yx5zBsrVJqRFvD1IpLko1iMLpB8+AXSyilZKDZj3luuDKXJKwZrAGBJZANIp0mrxmFHSQX4rNQKBgQDVK1tLj8zx6LjAxXnxxySkM+SPb6TPFzRDFJweo5m8YrptVUGnOztJqfH8zlCjjaZ6G4dbib4z8rDk/6WiULw1z5HQr93O9TprITCQI7JbGylmNSjf3UPLGB7xl/ZbRW/ta6irw8jojPziY98uDP0oGDTFgS1i0z2Zr7HklGwrZQKBgQCZxH0XJXNwp2171Bff+brdq11Qj9drDDlwt/1gHR5EE7VytcFqWLBnoD2UNC49Jgn2cSwnA/kyINQQ1CxE0k2mogNuHIdDBrSovwL5x1d2Q/dd2JNbr88rHEmrs5NrJZg+/7hGkgHxedlw/ESVUH4/91DrqP6xsQoTsy3BHIBcdQKBgDe7AIQF8tCXWQ/TV+UAkIdfKg5lI/UWzzbvBctUWzgnIStcLVqL2K1nclsZxLKdtVvzInHidrXedF23xjHWN2E9Lkmz6ioQ+suvrKVZmnsxfVyrUjjfP+R5fhgCB4ISYcV6f4YLecgDjhGtkR6JUbSlR8MMX+fVUXNQyefezirY}
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0knvtRm+iR1b2a4ElJTZ7FpIfI7ADrTLVYaKZMW0U5643LhwgnbgnSeSNb3UWnonvF2mpAOt2lIoNLQ9U2yv/5fJh9CMxmUI4V4+Ht4LqxavQNKuYklOuQcFcNyvr5LYCr8qV3600H7/GxUIC3m+UW3F3JXXrJ/AXmUZBtf8uzxXDIcyQ9V7cFCx1b5d/XMNmRFXPAmJMs7q7z2RHC8vRhtcz3VdR+PL7vcmxM9mrW86qQmImpVZOjnpSBh20/+VyCrorHTIl6zuD2AY7KMacHKYvnGQxQpu9RT609j9vcKOrF+0defldfv4zFYrWA46PuWgzah5G/PhIkfHmDGCzwIDAQAB}
  security:
    login-rate-limit-count: 5
    login-rate-limit-window-seconds: 60
  verification:
    token-minutes: 30
    base-url: ${VERIFICATION_BASE_URL:http://localhost:8090}
    path: /auth/verify-email
  password-reset:
    token-minutes: 30
    base-url: ${PASSWORD_RESET_BASE_URL:http://localhost:8090}
    path: /auth/password-reset/confirm
  kafka:
    topic:
      email-events: notification.email.events

logging:
  level:
    root: INFO
    com.ordernest.sso: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
